package io.github.wendlmax.reaktor.ts;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Core engine traversing Java metadata representations and compiling them
 * dynamically into standard strictly-typed TypeScript declarations.
 *
 * @since 0.1.0
 */
public class ReaktorTypeScriptGenerator {

    private static final Logger log = LoggerFactory.getLogger(ReaktorTypeScriptGenerator.class);

    /**
     * Scans the provided classes, generates TypeScript interfaces for those
     * annotated
     * with @GenerateTS, and writes them to the specified output file.
     *
     * @param classes    List of classes to scan (usually from reflections)
     * @param outputPath The file path where reaktor-types.d.ts will be written
     */
    public static void generate(List<Class<?>> classes, String outputPath) {
        StringBuilder tsOutput = new StringBuilder();
        tsOutput.append("/**\n");
        tsOutput.append(" * Auto-generated by ReaktorTypeScriptGenerator\n");
        tsOutput.append(" * Do not edit this file manually.\n");
        tsOutput.append(" */\n\n");

        int count = 0;
        for (Class<?> clazz : classes) {
            GenerateTS annotation = clazz.getAnnotation(GenerateTS.class);
            if (annotation != null) {
                String interfaceName = annotation.name().isEmpty() ? clazz.getSimpleName() : annotation.name();
                tsOutput.append("export interface ").append(interfaceName).append(" {\n");

                for (Field field : clazz.getDeclaredFields()) {
                    if (Modifier.isStatic(field.getModifiers()) || Modifier.isTransient(field.getModifiers())) {
                        continue;
                    }

                    String tsType = mapJavaTypeToTS(field.getGenericType());
                    tsOutput.append("    ").append(field.getName()).append(": ").append(tsType).append(";\n");
                }

                tsOutput.append("}\n\n");
                count++;
            }
        }

        if (count == 0) {
            log.info("No classes annotated with @GenerateTS found. Skipping TS generation.");
            return;
        }

        try {
            File outputFile = new File(outputPath);
            outputFile.getParentFile().mkdirs();
            try (FileWriter writer = new FileWriter(outputFile, false)) {
                writer.write(tsOutput.toString());
            }
            log.info("Successfully generated TypeScript types for {} classes at: {}", count, outputPath);
        } catch (IOException e) {
            log.error("Failed to write TypeScript definitions to {}", outputPath, e);
        }
    }

    private static String mapJavaTypeToTS(Type type) {
        if (type instanceof Class<?> clazz) {
            if (clazz.equals(String.class) || clazz.equals(char.class) || clazz.equals(Character.class)
                    || clazz.equals(java.util.UUID.class)) {
                return "string";
            }
            if (Number.class.isAssignableFrom(clazz) || clazz.equals(int.class) || clazz.equals(long.class)
                    || clazz.equals(double.class) || clazz.equals(float.class) || clazz.equals(short.class)
                    || clazz.equals(byte.class)) {
                return "number";
            }
            if (clazz.equals(Boolean.class) || clazz.equals(boolean.class)) {
                return "boolean";
            }
            if (Date.class.isAssignableFrom(clazz) || java.time.temporal.Temporal.class.isAssignableFrom(clazz)) {
                return "string"; // Ser/De usually maps Date/LocalTime to ISO-8601 Strings
            }
            if (clazz.isArray()) {
                return mapJavaTypeToTS(clazz.getComponentType()) + "[]";
            }

            // If it's another domain class that might be annotated
            if (clazz.getAnnotation(GenerateTS.class) != null) {
                GenerateTS ann = clazz.getAnnotation(GenerateTS.class);
                return ann.name().isEmpty() ? clazz.getSimpleName() : ann.name();
            }

            return "any";
        }

        if (type instanceof ParameterizedType pType) {
            Type rawType = pType.getRawType();
            if (rawType instanceof Class<?> rawClass) {
                if (Collection.class.isAssignableFrom(rawClass)) {
                    Type[] typeArgs = pType.getActualTypeArguments();
                    if (typeArgs.length > 0) {
                        return mapJavaTypeToTS(typeArgs[0]) + "[]";
                    }
                    return "any[]";
                }
                if (Map.class.isAssignableFrom(rawClass)) {
                    Type[] typeArgs = pType.getActualTypeArguments();
                    if (typeArgs.length == 2) {
                        return "Record<" + mapJavaTypeToTS(typeArgs[0]) + ", " + mapJavaTypeToTS(typeArgs[1]) + ">";
                    }
                    return "Record<string, any>";
                }
            }
        }

        return "any";
    }
}
